#!/usr/bin/env python3
"""Ticket registry — load/save/validate/sync for tickets/registry.json."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

AUTO_HEADER = "<!-- AUTO-GENERATED by ./scripts/ticket sync — DO NOT EDIT -->\n\n"

FORBIDDEN_PHANTOM_IDS = frozenset(
    {
        "T-007",
        "T-014", "T-015", "T-016", "T-017",
        "T-026", "T-027", "T-028",
        "T-041", "T-042", "T-044",
        "T-051",
    }
)

STRICT_LEGACY = re.compile(
    r"\bP[0-3]-[0-9]{2}\b|\bP[0-3]-0[0-9]\b"
    r"|Eden P[0-3]|Eden P0|P0–P2|P0-P3|P0–P3"
    r"|\bP0 registry\b|\bP1 feel\b"
    r"|\bFD-0[0-9]{1,2}\b|\bFD-0xx\b|\bFD backlog\b"
    r"|\bBE-0[0-9]{1,2}\b|\bBE-0xx\b|\bBE backlog\b"
    r"|Track [ABC]\b|Tracks [ABC]/[ABC]/[ABC]|Tracks [ABC]/[ABC]"
    r"|\bA-0[0-9]\b|\bB-0[0-9]\b|\bC-0[0-9]\b"
    r"|\"gap\":\s*\"P[0-3]-"
)

EXEMPT_SCAN_PREFIXES = (
    "artifacts/eden-wiki/",
    "frontend/src/stitch-exports/",
    "Design_Docs/macOS_Blueprints/",
    "Mission_Creator_Mock_Up/",
    ".stitch-backup-exports/",
)

STATUS_MARKER_START = "<!-- ticket-sync:status:start -->"
STATUS_MARKER_END = "<!-- ticket-sync:status:end -->"
NEXT_MARKER_START = "<!-- ticket-sync:next:start -->"
NEXT_MARKER_END = "<!-- ticket-sync:next:end -->"


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def registry_path() -> Path:
    return repo_root() / "tickets" / "registry.json"


def schema_path() -> Path:
    return repo_root() / "tickets" / "schema.json"


def gap_analysis_path() -> Path:
    return (
        repo_root()
        / "Design_Docs/Mission_Creator_Architecture/eden/gap_analysis.md"
    )


def load_registry() -> dict[str, Any]:
    path = registry_path()
    if not path.is_file():
        sys.stderr.write(f"Missing registry: {path}\n")
        sys.exit(1)
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def save_registry(data: dict[str, Any]) -> None:
    path = registry_path()
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def load_schema() -> dict[str, Any]:
    with schema_path().open(encoding="utf-8") as f:
        return json.load(f)


def ticket_by_id(data: dict[str, Any], tid: str) -> dict[str, Any] | None:
    for t in data.get("tickets", []):
        if t.get("id") == tid:
            return t
    return None


def validate_row(row: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    status = row.get("status", "")
    required_all = {"id", "title", "summary", "program", "surfaces", "impact", "status"}
    for key in required_all:
        if not row.get(key):
            errors.append(f"{row.get('id', '?')}: missing {key}")
    if status != "idea" and not row.get("order"):
        errors.append(f"{row.get('id')}: order required for status {status}")
    if row.get("id") in FORBIDDEN_PHANTOM_IDS:
        errors.append(f"Forbidden phantom id {row['id']}")
    return errors


def validate_registry(data: dict[str, Any] | None = None) -> list[str]:
    data = data or load_registry()
    errors: list[str] = []
    ids: set[str] = set()
    for row in data.get("tickets", []):
        errors.extend(validate_row(row))
        tid = row.get("id")
        if tid in ids:
            errors.append(f"Duplicate id {tid}")
        ids.add(tid)
    return errors


@dataclass
class GapTable:
    start_line: int
    end_line: int
    header_line: str
    separator_line: str
    rows: list[list[str]]
    raw_rows: list[str]


@dataclass
class GapAnalysisDoc:
    lines: list[str]
    tables: list[GapTable] = field(default_factory=list)


def _split_table_row(line: str) -> list[str]:
    inner = line.strip()
    if not inner.startswith("|"):
        return []
    inner = inner.strip("|")
    return [c.strip() for c in inner.split("|")]


def parse_gap_analysis_tables(content: str | None = None) -> GapAnalysisDoc:
    if content is None:
        content = gap_analysis_path().read_text(encoding="utf-8")
    lines = content.splitlines(keepends=True)
    doc = GapAnalysisDoc(lines=lines)
    i = 0
    while i < len(lines):
        line = lines[i]
        if "| eden_id |" in line and "priority |" in line:
            header_line = line
            sep_line = lines[i + 1] if i + 1 < len(lines) else ""
            if not re.match(r"^\|\s*-+\s*\|", sep_line.strip()):
                i += 1
                continue
            rows: list[list[str]] = []
            raw_rows: list[str] = []
            j = i + 2
            while j < len(lines):
                row_line = lines[j]
                if not row_line.strip().startswith("|"):
                    break
                if re.match(r"^\|\s*-+\s*\|", row_line.strip()):
                    break
                cells = _split_table_row(row_line)
                if len(cells) >= 5:
                    rows.append(cells)
                    raw_rows.append(row_line)
                j += 1
            doc.tables.append(
                GapTable(
                    start_line=i,
                    end_line=j - 1,
                    header_line=header_line,
                    separator_line=sep_line,
                    rows=rows,
                    raw_rows=raw_rows,
                )
            )
            i = j
            continue
        i += 1
    return doc


def write_gap_analysis_tables(doc: GapAnalysisDoc, *, ticket_column: bool = False) -> str:
    lines = list(doc.lines)
    offset = 0
    for table in doc.tables:
        start = table.start_line + offset
        end = table.end_line + offset
        new_block: list[str] = []
        header = table.header_line
        if ticket_column:
            header = header.replace("priority |", "ticket |")
        new_block.append(header)
        new_block.append(table.separator_line)
        for row_cells, raw in zip(table.rows, table.raw_rows, strict=True):
            if ticket_column and len(row_cells) >= 5:
                cells = list(row_cells)
                new_line = "| " + " | ".join(cells) + " |"
                if raw.endswith("\n"):
                    new_line += "\n"
                new_block.append(new_line)
            else:
                new_block.append(raw)
        lines[start : end + 1] = new_block
        offset += len(new_block) - (end - start + 1)
    return "".join(lines)


def test_gap_analysis_round_trip(path: Path | None = None) -> None:
    path = path or gap_analysis_path()
    original = path.read_text(encoding="utf-8")
    doc = parse_gap_analysis_tables(original)
    round_trip = write_gap_analysis_tables(doc, ticket_column=False)
    if round_trip != original:
        raise RuntimeError(
            f"gap_analysis round-trip failed: {len(original)} vs {len(round_trip)} bytes"
        )


def _lookup_ticket_for_gap(registry: dict[str, Any], eden_id: str, tbd_id: str, gap_notes: str) -> str:
    m = re.search(r"✅\s*(T-\d{3})", gap_notes)
    if m:
        return m.group(1)
    for row in registry.get("tickets", []):
        impl = row.get("implements") or []
        if eden_id in impl or tbd_id in impl:
            return row["id"]
    mapping = {
        "PLACE-004": "T-072",
        "XFORM-SHIFT-001": "T-073",
        "XFORM-ROT-001": "T-073",
        "RIGHT-SUBMODE-001": "T-074",
        "WIDGET-CYCLE-001": "T-075",
        "CREW-PANEL-001": "T-076",
        "CREW-BOARD-001": "T-076",
        "PLACE-CREW-001": "T-077",
        "COMP-SAVE-001": "T-078",
        "COMP-PLACE-001": "T-078",
        "RIGHT-MODE-001": "T-068",
        "RIGHT-CAT-001": "T-068",
        "RIGHT-MODE-006": "T-069",
        "RIGHT-STUB-002": "T-069",
        "CONN-GROUP-001": "T-071",
        "LEFT-ORBAT-001": "T-071",
        "RIGHT-SEARCH-001": "T-055",
        "SEL-MOD-001": "T-053",
        "SEL-ORBAT-DBL-001": "T-054",
        "ATTR-FIELD-OBJ-POSITION": "T-049",
        "ATTR-TAB-001": "T-049",
        "MAP-TERRAIN-001": "T-049",
        "DATA-HYD-TITLE-001": "T-049",
        "TOP-TITLE-001": "T-049",
        "TOP-UNDO-001": "T-052",
        "TOOLBAR-UNDO-001": "T-052",
    }
    if eden_id in mapping:
        return mapping[eden_id]
    if tbd_id in mapping:
        return mapping[tbd_id]
    return "—"


def sync_gap_analysis_ticket_column(registry: dict[str, Any] | None = None) -> None:
    test_gap_analysis_round_trip()
    registry = registry or load_registry()
    path = gap_analysis_path()
    original = path.read_text(encoding="utf-8")
    doc = parse_gap_analysis_tables(original)
    for table in doc.tables:
        for row in table.rows:
            if len(row) >= 5:
                row[3] = _lookup_ticket_for_gap(registry, row[0], row[1], row[4])
    updated = write_gap_analysis_tables(doc, ticket_column=True)
    path.write_text(updated, encoding="utf-8")


def inject_marker_block(path: Path, start: str, end: str, inner: str) -> None:
    text = path.read_text(encoding="utf-8")
    if start not in text or end not in text:
        raise RuntimeError(f"Missing markers in {path}: {start} / {end}")
    before, rest = text.split(start, 1)
    _, after = rest.split(end, 1)
    new_text = before + start + "\n" + inner.rstrip() + "\n" + end + after
    path.write_text(new_text, encoding="utf-8")


def inject_status_block(registry: dict[str, Any] | None = None) -> None:
    registry = registry or load_registry()
    tickets = registry.get("tickets", [])
    shipped = [t for t in tickets if t.get("status") == "shipped"]
    shipped.sort(key=lambda t: t.get("order", 9999), reverse=True)
    latest = shipped[0]["id"] if shipped else "T-066"
    slice_row = next((t for t in tickets if t.get("active_slice")), None)
    lines = [f"**Latest shipped:** **{latest}**", ""]
    if slice_row:
        lines.append(
            f"**ACTIVE NOW:** **{slice_row['id']}** — {slice_row.get('active_slice', '')} "
            f"({slice_row.get('title', '')}). Spec: `{slice_row.get('spec', '')}`."
        )
    else:
        ready = sorted(
            [t for t in tickets if t.get("status") == "ready"],
            key=lambda t: t.get("order", 9999),
        )
        if ready:
            r = ready[0]
            lines.append(f"**ACTIVE NOW:** **{r['id']}** — {r.get('title', '')}")
    lines.append("")
    lines.append("**Next (by order):**")
    queued = [
        t for t in tickets if t.get("status") in ("queued", "ready") and t.get("order")
    ]
    queued.sort(key=lambda t: t.get("order", 9999))
    for t in queued[:10]:
        lines.append(f"- **{t['id']}** — {t.get('title', '')} (`{t.get('status')}`)")
    inject_marker_block(
        repo_root() / "CLAUDE.md", STATUS_MARKER_START, STATUS_MARKER_END, "\n".join(lines)
    )


def inject_next_block(registry: dict[str, Any] | None = None) -> None:
    registry = registry or load_registry()
    lines = ["### Recommended next work (auto-generated)", ""]
    open_t = [
        t
        for t in registry.get("tickets", [])
        if t.get("status") in ("ready", "queued", "running", "review")
        and t.get("order")
    ]
    open_t.sort(key=lambda t: (t.get("order", 9999), t.get("id", "")))
    for t in open_t[:10]:
        lines.append(f"- **{t['id']}** — {t.get('title', '')} ({t.get('status')})")
    inject_marker_block(
        repo_root() / "Design_Docs/Mission_Creator_Architecture/ROADMAP.md",
        NEXT_MARKER_START,
        NEXT_MARKER_END,
        "\n".join(lines),
    )


def _ticket_sort_key(t: dict[str, Any]) -> tuple[int, str]:
    return (t.get("order") or 99999, t.get("id", ""))


def generate_ticket_registry_md(registry: dict[str, Any] | None = None) -> str:
    registry = registry or load_registry()
    rows = sorted(registry.get("tickets", []), key=_ticket_sort_key)
    lines = [
        AUTO_HEADER,
        "# Ticket Registry",
        "",
        "| T-ID | Order | Status | Program | Title | Summary |",
        "|------|-------|--------|---------|-------|---------|",
    ]
    for t in rows:
        summary = (t.get("summary") or "").replace("|", "\\|")
        lines.append(
            f"| {t['id']} | {t.get('order', '—')} | {t['status']} | {t.get('program', '')} | "
            f"{t.get('title', '')} | {summary} |"
        )
    lines.append("")
    return "\n".join(lines)


def generate_ticket_lead_md(registry: dict[str, Any] | None = None) -> str:
    registry = registry or load_registry()
    tickets = registry.get("tickets", [])
    lines = [AUTO_HEADER, "# Ticket Lead Dashboard", ""]
    for label, statuses in (
        ("Running / Review", ("running", "review")),
        ("Ready", ("ready",)),
        ("Next queued (top 10)", ("queued",)),
    ):
        subset = [t for t in tickets if t.get("status") in statuses]
        subset.sort(key=_ticket_sort_key)
        if label.startswith("Next"):
            subset = subset[:10]
        lines.append(f"## {label}")
        lines.append("")
        for t in subset:
            lines.append(
                f"- **{t['id']}** ({t.get('order', '—')}) — {t.get('title', '')} "
                f"[{t.get('status')}] — {t.get('summary', '')}"
            )
        lines.append("")
    lines.append("## Dependency graph (scoped)")
    lines.append("")
    lines.append("```mermaid")
    lines.append("flowchart LR")
    graph_ids: set[str] = set()
    for t in tickets:
        if t.get("status") in ("running", "review", "ready"):
            graph_ids.add(t["id"])
    queued = sorted(
        [t for t in tickets if t.get("status") == "queued" and t.get("order")],
        key=_ticket_sort_key,
    )[:5]
    for t in queued:
        graph_ids.add(t["id"])
    for t in tickets:
        if t.get("status") == "shipped":
            for other in tickets:
                if other["id"] in graph_ids and t["id"] in (other.get("depends_on") or []):
                    graph_ids.add(t["id"])
    for t in tickets:
        if t["id"] not in graph_ids:
            continue
        for dep in t.get("depends_on") or []:
            if dep in graph_ids:
                dep_n = dep.replace("-", "")
                tid_n = t["id"].replace("-", "")
                lines.append(f"  {dep_n}[{dep}] --> {tid_n}[{t['id']}]")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def generate_ticket_dev_queue_md(registry: dict[str, Any] | None = None) -> str:
    registry = registry or load_registry()
    ready = [t for t in registry.get("tickets", []) if t.get("status") == "ready"]
    ready.sort(key=_ticket_sort_key)
    lines = [AUTO_HEADER, "# Developer Queue", "", "Only `ready` tickets with specs.", ""]
    for t in ready:
        tid = t["id"]
        branch = t.get("branch", f"ticket/{tid}")
        lines.append(f"## {tid} — {t.get('title', '')}")
        lines.append("")
        lines.append(f"- **Spec:** `{t.get('spec', '')}`")
        lines.append(f"- **Branch:** `{branch}`")
        lines.append(f"- **Summary:** {t.get('summary', '')}")
        lines.append("")
    return "\n".join(lines)


def generate_ticket_brainstorm_md(registry: dict[str, Any] | None = None) -> str:
    registry = registry or load_registry()
    lines = [AUTO_HEADER, "# Ticket Brainstorm", "", "`idea` + `deferred` only.", ""]
    by_program: dict[str, list[dict[str, Any]]] = {}
    for t in registry.get("tickets", []):
        if t.get("status") not in ("idea", "deferred"):
            continue
        by_program.setdefault(t.get("program", "platform"), []).append(t)
    for program in sorted(by_program):
        lines.append(f"## {program}")
        lines.append("")
        for t in sorted(by_program[program], key=_ticket_sort_key):
            surfaces = ", ".join(t.get("surfaces") or [])
            lines.append(
                f"- **{t['id']}** ({t.get('status')}) — {t.get('title', '')} "
                f"[{surfaces}] — {t.get('summary', '')}"
            )
        lines.append("")
    return "\n".join(lines)


def generate_queue_json(registry: dict[str, Any] | None = None) -> dict[str, Any]:
    registry = registry or load_registry()
    pipeline = [
        t
        for t in registry.get("tickets", [])
        if t.get("status") in ("ready", "running", "review")
        and (t.get("spec") or "").strip()
    ]
    pipeline.sort(key=_ticket_sort_key)
    tickets = []
    for t in pipeline:
        tickets.append(
            {
                "id": t["id"],
                "title": t.get("title", ""),
                "status": t.get("status"),
                "spec": t.get("spec", ""),
                "branch": t.get("branch", f"ticket/{t['id']}"),
            }
        )
    return {
        "_comment": AUTO_HEADER.strip(),
        "batch_size": 10,
        "concurrency": 3,
        "worktree_base": "../worktrees",
        "git_base": "main",
        "tickets": tickets,
    }


def scan_legacy_ids() -> dict[str, list[str]]:
    root = repo_root()
    hits: dict[str, list[str]] = {}
    scan_roots = [
        root / "docs",
        root / "Design_Docs",
        root / "frontend" / "docs",
        root / "frontend" / "src",
        root / "tickets" / "queue.json",
        root / "CLAUDE.md",
        root / "README.md",
    ]
    for base in scan_roots:
        files = [base] if base.is_file() else [p for p in base.rglob("*") if p.is_file()]
        for f in files:
            rel = str(f.relative_to(root)).replace("\\", "/")
            if any(rel.startswith(p) or p in rel for p in EXEMPT_SCAN_PREFIXES):
                continue
            if rel == "docs/REORG_CHANGELOG.md":
                continue
            try:
                text = f.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            matches = STRICT_LEGACY.findall(text)
            if matches:
                hits[rel] = matches
    return hits


def check(strict: bool = False, seed_count: int | None = None) -> list[str]:
    errors = validate_registry()
    registry = load_registry()
    root = repo_root()

    if seed_count is not None and len(registry.get("tickets", [])) != seed_count:
        errors.append(f"Expected {seed_count} registry rows, got {len(registry.get('tickets', []))}")

    expected_rows = 85  # 54 shipped + 31 open
    if len(registry.get("tickets", [])) != expected_rows:
        errors.append(
            f"Registry row count must be {expected_rows} (54 shipped + 31 open), "
            f"got {len(registry.get('tickets', []))}"
        )

    for tid in FORBIDDEN_PHANTOM_IDS:
        if ticket_by_id(registry, tid):
            errors.append(f"Forbidden phantom ticket row: {tid}")

    for row in registry.get("tickets", []):
        spec = (row.get("spec") or "").strip()
        if spec and row.get("status") not in ("idea", "cancelled"):
            if not (root / spec).is_file():
                errors.append(f"{row['id']}: spec missing on disk: {spec}")

    claude = root / "CLAUDE.md"
    roadmap = root / "Design_Docs/Mission_Creator_Architecture/ROADMAP.md"
    for p, start, end in (
        (claude, STATUS_MARKER_START, STATUS_MARKER_END),
        (roadmap, NEXT_MARKER_START, NEXT_MARKER_END),
    ):
        if p.is_file():
            text = p.read_text(encoding="utf-8")
            if start not in text or end not in text:
                errors.append(f"Missing markers in {p.relative_to(root)}")

    try:
        test_gap_analysis_round_trip()
    except RuntimeError as e:
        errors.append(str(e))

    if strict:
        hits = scan_legacy_ids()
        for path, matches in hits.items():
            errors.append(f"Legacy ID in {path}: {len(matches)} match(es)")

        gap = gap_analysis_path()
        if gap.is_file():
            text = gap.read_text(encoding="utf-8")
            if "| priority |" in text or re.search(r"^\d+\.\s+\*\*P[0-3]", text, re.M):
                errors.append("gap_analysis still has priority column or numbered P backlog")

    return errors


def cmd_sync(_: argparse.Namespace) -> None:
    registry = load_registry()
    root = repo_root()
    (root / "docs").mkdir(parents=True, exist_ok=True)

    (root / "docs/TICKET_REGISTRY.md").write_text(
        generate_ticket_registry_md(registry), encoding="utf-8"
    )
    (root / "docs/TICKET_LEAD.md").write_text(
        generate_ticket_lead_md(registry), encoding="utf-8"
    )
    (root / "docs/TICKET_DEV_QUEUE.md").write_text(
        generate_ticket_dev_queue_md(registry), encoding="utf-8"
    )
    (root / "docs/TICKET_BRAINSTORM.md").write_text(
        generate_ticket_brainstorm_md(registry), encoding="utf-8"
    )

    queue = generate_queue_json(registry)
    with (root / "tickets/queue.json").open("w", encoding="utf-8") as f:
        json.dump(queue, f, indent=2)
        f.write("\n")

    claude = root / "CLAUDE.md"
    roadmap = root / "Design_Docs/Mission_Creator_Architecture/ROADMAP.md"
    if claude.is_file() and STATUS_MARKER_START in claude.read_text(encoding="utf-8"):
        inject_status_block(registry)
    if roadmap.is_file() and NEXT_MARKER_START in roadmap.read_text(encoding="utf-8"):
        inject_next_block(registry)

    if gap_analysis_path().is_file():
        sync_gap_analysis_ticket_column(registry)

    print("sync complete")


def cmd_check(args: argparse.Namespace) -> None:
    errors = check(strict=args.strict)
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    print("check OK")


def cmd_brief(args: argparse.Namespace) -> None:
    registry = load_registry()
    t = ticket_by_id(registry, args.id)
    if not t:
        sys.stderr.write(f"Unknown ticket: {args.id}\n")
        sys.exit(1)
    spec = t.get("spec", "")
    tid = t["id"]
    branch = t.get("branch", f"ticket/{tid}")
    print(f"{tid} · {t.get('title', '')}")
    print(f"READ: {spec} (only source of truth)")
    print(f"BRANCH: {branch}")
    print("DO NOT: edit documentation")
    print("VERIFY: cd frontend && npm run build && npm run lint")
    if t.get("acceptance"):
        print("ACCEPTANCE:")
        for a in t["acceptance"]:
            print(f"  - {a}")


def cmd_next(_: argparse.Namespace) -> None:
    registry = load_registry()
    slice_row = next((t for t in registry["tickets"] if t.get("active_slice")), None)
    if slice_row:
        print(f"ACTIVE: {slice_row['id']} slice {slice_row.get('active_slice')}")
    open_t = [
        t
        for t in registry["tickets"]
        if t.get("status") in ("ready", "queued") and t.get("order")
    ]
    open_t.sort(key=_ticket_sort_key)
    for t in open_t[:5]:
        print(f"  {t['id']} — {t.get('title')} ({t.get('status')})")


def cmd_ship(args: argparse.Namespace) -> None:
    registry = load_registry()
    t = ticket_by_id(registry, args.id)
    if not t:
        sys.stderr.write(f"Unknown ticket: {args.id}\n")
        sys.exit(1)
    t["status"] = "shipped"
    t.pop("active_slice", None)
    save_registry(registry)
    cmd_sync(argparse.Namespace())
    print(f"{args.id} -> shipped")


def cmd_mark_ready(args: argparse.Namespace) -> None:
    registry = load_registry()
    t = ticket_by_id(registry, args.id)
    if not t:
        sys.stderr.write(f"Unknown ticket: {args.id}\n")
        sys.exit(1)
    if args.spec:
        t["spec"] = args.spec
    spec = (t.get("spec") or "").strip()
    if not spec:
        sys.stderr.write(f"Ticket {args.id} needs a spec path\n")
        sys.exit(1)
    root = repo_root()
    if not (root / spec).is_file():
        sys.stderr.write(f"Spec file not found: {root / spec}\n")
        sys.exit(1)
    for dep in t.get("depends_on") or []:
        dep_row = ticket_by_id(registry, dep)
        if dep_row and dep_row.get("status") not in ("shipped", "cancelled"):
            sys.stderr.write(f"Blocked by {dep} (status={dep_row.get('status')})\n")
            sys.exit(1)
    t["status"] = "ready"
    save_registry(registry)
    cmd_sync(argparse.Namespace())
    print(f"{args.id} -> ready ({spec})")


def cmd_show(args: argparse.Namespace) -> None:
    registry = load_registry()
    t = ticket_by_id(registry, args.id)
    if not t:
        sys.stderr.write(f"Unknown ticket: {args.id}\n")
        sys.exit(1)
    surfaces = ", ".join(t.get("surfaces") or [])
    impact = ", ".join(t.get("impact") or [])
    print(f"### {t['id']} · {t.get('title', '')}")
    print(f"**Program:** {t.get('program')} · **Where:** {surfaces}")
    if t.get("route"):
        print(f"**Route:** {t['route']}")
    print(f"**Impact:** {impact} · **Status:** {t.get('status')} · **Order:** {t.get('order', '—')}")
    print(f"**Summary:** {t.get('summary', '')}")
    if t.get("depends_on"):
        print(f"**Needs:** {', '.join(t['depends_on'])}")
    if t.get("unblocks"):
        print(f"**Blocks:** {', '.join(t['unblocks'])}")
    if t.get("spec"):
        print(f"**Spec:** `{t['spec']}`")


def cmd_add(args: argparse.Namespace) -> None:
    registry = load_registry()
    tid = f"T-{registry['next_id']:03d}"
    registry["next_id"] += 1
    row: dict[str, Any] = {
        "id": tid,
        "title": args.title,
        "summary": args.summary or args.title,
        "program": args.program,
        "surfaces": args.surfaces.split(","),
        "impact": args.impact.split(","),
        "status": "idea",
    }
    registry["tickets"].append(row)
    save_registry(registry)
    cmd_sync(argparse.Namespace())
    print(f"Added {tid}: {args.title}")


def cmd_remove(args: argparse.Namespace) -> None:
    registry = load_registry()
    before = len(registry["tickets"])
    registry["tickets"] = [t for t in registry["tickets"] if t.get("id") != args.id]
    if len(registry["tickets"]) == before:
        sys.stderr.write(f"Unknown ticket: {args.id}\n")
        sys.exit(1)
    save_registry(registry)
    cmd_sync(argparse.Namespace())
    print(f"Removed {args.id}")


def cmd_reorder(args: argparse.Namespace) -> None:
    registry = load_registry()
    t = ticket_by_id(registry, args.id)
    if not t:
        sys.stderr.write(f"Unknown ticket: {args.id}\n")
        sys.exit(1)
    after_id = args.after.replace("--after", "").strip() if hasattr(args, "after") else None
    anchor = ticket_by_id(registry, args.after)
    if not anchor or anchor.get("order") is None:
        sys.stderr.write(f"Unknown anchor ticket: {args.after}\n")
        sys.exit(1)
    t["order"] = anchor["order"] + 1
    if t.get("status") == "idea":
        t["status"] = "queued"
    save_registry(registry)
    cmd_sync(argparse.Namespace())
    print(f"{args.id} order -> {t['order']} (after {args.after})")


def cmd_plan_batch(_: argparse.Namespace) -> None:
    registry = load_registry()
    queued = [
        t for t in registry["tickets"]
        if t.get("status") in ("queued", "ready") and t.get("order")
    ]
    queued.sort(key=_ticket_sort_key)
    print("Next batch candidates (top 10 by order):")
    for t in queued[:10]:
        spec = t.get("spec") or "(no spec yet)"
        print(f"  {t['id']} — {t.get('title')} [{t.get('status')}] — {spec}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Ticket registry operations")
    sub = parser.add_subparsers(dest="cmd")

    sub.add_parser("sync").set_defaults(func=cmd_sync)

    p_check = sub.add_parser("check")
    p_check.add_argument("--strict", action="store_true")
    p_check.set_defaults(func=cmd_check)

    p_brief = sub.add_parser("brief")
    p_brief.add_argument("id")
    p_brief.set_defaults(func=cmd_brief)

    sub.add_parser("next").set_defaults(func=cmd_next)

    p_ship = sub.add_parser("ship")
    p_ship.add_argument("id")
    p_ship.set_defaults(func=cmd_ship)

    p_mr = sub.add_parser("mark-ready")
    p_mr.add_argument("id")
    p_mr.add_argument("spec", nargs="?", default="")
    p_mr.set_defaults(func=cmd_mark_ready)

    p_show = sub.add_parser("show")
    p_show.add_argument("id")
    p_show.set_defaults(func=cmd_show)

    p_add = sub.add_parser("add")
    p_add.add_argument("title")
    p_add.add_argument("--program", default="eden")
    p_add.add_argument("--surfaces", default="MAP")
    p_add.add_argument("--impact", default="ui")
    p_add.add_argument("--summary", default="")
    p_add.set_defaults(func=cmd_add)

    p_rm = sub.add_parser("remove")
    p_rm.add_argument("id")
    p_rm.set_defaults(func=cmd_remove)

    p_re = sub.add_parser("reorder")
    p_re.add_argument("id")
    p_re.add_argument("after")
    p_re.set_defaults(func=cmd_reorder)

    sub.add_parser("plan-batch").set_defaults(func=cmd_plan_batch)

    sub.add_parser("gap-round-trip").set_defaults(
        func=lambda _: (test_gap_analysis_round_trip(), print("round-trip OK"))[-1]
    )

    args = parser.parse_args()
    if not args.cmd:
        parser.print_help()
        sys.exit(1)
    args.func(args)


if __name__ == "__main__":
    main()
