/** Historical reference mapping for Stitch folders; prefer live routes in frontend/src/pages. See frontend/docs/INDEX.md */
export const stitchMap: Record<string, string | null> = {
  '/': 'tbd_reforger_dashboard_content',
  '/server-intel': 'server_intel_dashboard',
  '/announcements': 'command_announcements_feed',
  '/deployments': 'my_deployments_service_record',
  '/leaderboards': 'global_leaderboards_player_rankings',
  '/missions': 'mission_library_tactical_browser',
  '/missions/:id': 'operation_enduring_freedom_mission_overview',
  '/missions/:id/edit': null,
  '/events': 'upcoming_operations_event_schedule',
  '/events/:id': null,
  '/events/:id/missions/:emid/orbat': null,
  '/vehicles': null,
  '/modpacks': 'server_modpacks_deployment_dependencies',
  '/wiki': 'sop_wiki_vehicle_database_iff',
  '/tools/mortar': 'mortar_calculator_tactical_view',
  '/admin/events': 'event_manager_admin_scheduling',
  '/admin/approvals': 'mission_approvals_queue_admin_dashboard',
  '/admin/server': null,
  '/admin/personnel': 'personnel_roster_admin_management',
  '/admin/content': 'content_manager_admin_cms',
  '/admin/audit': 'system_audit_logs_admin_console',
  '/settings': null,
  '/login': null,
  '/auth/callback': null,
}
